apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: selfbank-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: "api.adarsh.click"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: selfbank-api-service
                port:
                  number: 80
